Update ListQues.py
ChimichangasBoi/sample pull request #3
Opened 2023-06-05 07:31 UTC by ChimichangasBoi

2023-06-05 08:24 UTC, tejas-k3 requested changes
Do the changes as per comment

2023-06-05 08:24 UTC, tejas-k3 commented on ListQues.py
> +    max = k[0] #assuming any element to be max then later get compared with other values for battle of death
What if I pass empty list? ([]), also use proper variable name instead of x more appropriate is elements or ele

2023-06-05 08:24 UTC, tejas-k3 commented on ListQues.py
> +print(bool(k.sort))
Dont use inbuilt method to find if it's sorted*, write your own logic

2023-06-20 15:36 UTC, tejas-k3 requested changes

2023-06-20 15:36 UTC, tejas-k3 commented on ListQues.py
>  #did some changes from scratch as there were some indention error
Remove comments, add comment above sorting function, one liner of what u are doing there.
Example :
# Iterate through given list of numbers and return largest number
def Max(k):

2023-06-20 15:43 UTC, ChimichangasBoi commented on ListQues.py
>  #did some changes from scratch as there were some indention error
got it

2023-08-03 15:53 UTC, merged